# Generated by Django 5.2.1 on 2025-06-23 05:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Audit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reference_number",
                    models.CharField(editable=False, max_length=10, unique=True),
                ),
                (
                    "audit_type",
                    models.CharField(
                        choices=[
                            ("internal", "Internal"),
                            ("external", "External"),
                            ("compliance", "Compliance"),
                            ("financial", "Financial"),
                            ("operational", "Operational"),
                            ("it", "IT"),
                            ("performance", "Performance"),
                        ],
                        default="internal",
                        max_length=20,
                    ),
                ),
                ("scope", models.TextField()),
                ("objectives", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planned", "Planned"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("closed", "Closed"),
                        ],
                        default="planned",
                        max_length=20,
                    ),
                ),
                ("period_from", models.DateField()),
                ("period_to", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_audits",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
