# Generated by Django 5.2.1 on 2025-06-23 05:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audits", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="audit",
            name="audit_type",
            field=models.CharField(
                choices=[
                    ("internal", "Internal"),
                    ("external", "External"),
                    ("compliance", "Compliance"),
                    ("financial", "Financial"),
                    ("operational", "Operational"),
                    ("it", "IT"),
                    ("performance", "Performance"),
                ],
                default="internal",
                max_length=100,
            ),
        ),
        migrations.CreateModel(
            name="CustomAuditType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_audit_types",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="audit",
            name="custom_audit_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="audits",
                to="audits.customaudittype",
            ),
        ),
    ]
