# Generated by Django 5.2.1 on 2025-06-23 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audits", "0002_alter_audit_audit_type_customaudittype_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="audit",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Audit",
                "verbose_name_plural": "Audits",
            },
        ),
        migrations.AlterModelOptions(
            name="customaudittype",
            options={
                "ordering": ["name"],
                "verbose_name": "Custom Audit Type",
                "verbose_name_plural": "Custom Audit Types",
            },
        ),
        migrations.AddField(
            model_name="audit",
            name="title",
            field=models.CharField(default="Untitled Audit", max_length=255),
        ),
    ]
