# Generated by Django 5.2.1 on 2025-06-23 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audits", "0004_audit_assigned_users_audit_workflow"),
    ]

    operations = [
        migrations.AlterField(
            model_name="audit",
            name="status",
            field=models.CharField(
                help_text="Current workflow state name", max_length=100
            ),
        ),
    ]
