# Generated by Django 5.2.1 on 2025-06-23 21:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audits", "0006_audittask_auditevidence"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "review_type",
                    models.CharField(
                        choices=[
                            ("task", "Task Review"),
                            ("evidence", "Evidence Review"),
                            ("final", "Final Audit Review"),
                        ],
                        max_length=20,
                        verbose_name="Review Type",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Review"),
                            ("in_review", "In Review"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("needs_revision", "Needs Revision"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Review Status",
                    ),
                ),
                (
                    "comments",
                    models.TextField(blank=True, verbose_name="Review Comments"),
                ),
                (
                    "internal_notes",
                    models.TextField(blank=True, verbose_name="Internal Notes"),
                ),
                (
                    "requested_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Requested At"
                    ),
                ),
                (
                    "due_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Review Due Date"
                    ),
                ),
                (
                    "reviewed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Reviewed At"
                    ),
                ),
                (
                    "review_criteria",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="JSON object containing review criteria and scores",
                        verbose_name="Review Criteria",
                    ),
                ),
                (
                    "overall_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        help_text="Score out of 10",
                        max_digits=3,
                        null=True,
                        verbose_name="Overall Score",
                    ),
                ),
                (
                    "approval_level",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Level in approval hierarchy",
                        verbose_name="Approval Level",
                    ),
                ),
                (
                    "is_final_approval",
                    models.BooleanField(
                        default=False, verbose_name="Is Final Approval"
                    ),
                ),
                (
                    "audit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="audits.audit",
                        verbose_name="Audit",
                    ),
                ),
                (
                    "audit_evidence",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="audits.auditevidence",
                        verbose_name="Audit Evidence",
                    ),
                ),
                (
                    "audit_task",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="audits.audittask",
                        verbose_name="Audit Task",
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="deleted_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="requested_reviews",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Requested By",
                    ),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="audit_reviews",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Reviewer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Audit Review",
                "verbose_name_plural": "Audit Reviews",
                "ordering": ["-requested_at"],
            },
        ),
        migrations.CreateModel(
            name="ReviewComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("content", models.TextField(verbose_name="Content")),
                (
                    "is_internal",
                    models.BooleanField(
                        default=False,
                        help_text="Internal comments only visible to reviewers",
                        verbose_name="Is Internal",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="review_comments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Author",
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="deleted_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replies",
                        to="audits.reviewcomment",
                        verbose_name="Parent Comment",
                    ),
                ),
                (
                    "review",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="review_comments",
                        to="audits.auditreview",
                        verbose_name="Review",
                    ),
                ),
            ],
            options={
                "verbose_name": "Review Comment",
                "verbose_name_plural": "Review Comments",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="ReviewTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Template Name"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "criteria",
                    models.JSONField(
                        default=list,
                        help_text="JSON array of criteria objects with name, description, weight, and scoring options",
                        verbose_name="Review Criteria",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                (
                    "review_type",
                    models.CharField(
                        choices=[
                            ("task", "Task Review"),
                            ("evidence", "Evidence Review"),
                            ("final", "Final Audit Review"),
                        ],
                        max_length=20,
                        verbose_name="Review Type",
                    ),
                ),
                (
                    "usage_count",
                    models.PositiveIntegerField(default=0, verbose_name="Usage Count"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_review_templates",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="deleted_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Review Template",
                "verbose_name_plural": "Review Templates",
                "ordering": ["name"],
            },
        ),
    ]
