# Generated by Django 5.2.1 on 2025-06-23 22:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audits", "0007_auditreview_reviewcomment_reviewtemplate"),
        ("checklists", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="auditevidence",
            name="checklist_field",
            field=models.ForeignKey(
                blank=True,
                help_text="Associate evidence with a specific checklist field",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="evidence",
                to="checklists.checklistfield",
                verbose_name="Checklist Field",
            ),
        ),
    ]
