# Generated by Django 5.2.1 on 2025-07-01 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audits", "0012_create_team_models"),
    ]

    operations = [
        migrations.AddField(
            model_name="audit",
            name="audit_item",
            field=models.CharField(
                blank=True,
                help_text="Specific item, process, or area being audited (e.g., Financial Statements, IT Security Controls, Quality Management System)",
                max_length=500,
                verbose_name="Audit Item",
            ),
        ),
    ]
