# Generated by Django 5.2.1 on 2025-06-25 17:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("checklists", "0002_multiple_user_assignment"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="checklist",
            name="assigned_to",
            field=models.ForeignKey(
                help_text="Legacy single user assignment - use assigned_users for multiple assignments",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="assigned_checklists",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Assigned To",
            ),
        ),
    ]
