# Generated by Django 5.2.1 on 2025-06-23 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("workflows", "0002_workflow_description_workflow_status_and_more"),
    ]

    operations = [
        migrations.RunSQL(
            sql="ALTER TABLE workflows_workflow DROP COLUMN transitions;",
            reverse_sql="ALTER TABLE workflows_workflow ADD COLUMN transitions JSON;",
        ),
    ]
