# Generated by Django 5.2.1 on 2025-06-07 18:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("files", "0001_initial"),
        ("user", "0003_alter_user_options_alter_user_language"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="picture",
            field=models.ForeignKey(
                blank=True,
                help_text="Profile picture for the user (must be type='user').",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="user_pictures",
                to="files.uploadedfile",
            ),
        ),
    ]
