# Generated by Django 4.2.1 on 2023-05-19 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Translation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=255, unique=True)),
                ("en", models.TextField(blank=True, null=True)),
                ("ar", models.TextField(blank=True, null=True)),
                (
                    "app",
                    models.CharField(
                        choices=[("ST", "Strategy")], default="ST", max_length=255
                    ),
                ),
            ],
        ),
    ]
