# Generated by Django 4.2.1 on 2024-02-23 14:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("translation", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="translation",
            name="app",
            field=models.CharField(
                choices=[("ST", "Strategy"), ("BC", "Budget Collection")],
                default="ST",
                max_length=255,
            ),
        ),
    ]
