# Generated by Django 4.2.1 on 2025-02-12 12:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("translation", "0002_alter_translation_app"),
    ]

    operations = [
        migrations.AlterField(
            model_name="translation",
            name="app",
            field=models.CharField(
                choices=[("BC", "Budget Collection"), ("ST", "Strategy")],
                default="BC",
                max_length=255,
            ),
        ),
    ]
