# Generated by Django 5.2.1 on 2025-06-01 04:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("translation", "0003_alter_translation_app"),
    ]

    operations = [
        migrations.AddField(
            model_name="translation",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="translation",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="translation",
            name="app",
            field=models.CharField(
                choices=[("audit", "Audit")], default="Audit", max_length=255
            ),
        ),
    ]
