# Generated by Django 5.2.1 on 2025-06-07 18:42

import apps.files.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("files", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="uploadedfile",
            name="file",
            field=models.FileField(
                upload_to=apps.files.models.upload_to_unique, verbose_name="File"
            ),
        ),
    ]
